# Generated by Django 3.2.25 on 2025-10-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_review_tablebooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ClientReview',
        ),
    ]
